version: '3'

services:
  # Service for NodeJS API

  # Service for Postgres Database
  server1:
    build: ./server_1
    container_name: server_1
    volumes:
      - ./server_1:/server_1
      # Postgres port 5432
    ports:
      - '8888:8888'
    stdin_open: true
    tty: true
  client:
    build: ./client
    container_name: client
    volumes:
      - ./client:/client
      # Postgres port 5432
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true